blog/urls.py
from django.urls import path

from .views import PageListView, PageView

app_name = "blog"
urlpatterns = [
    path("<int:pk>", PageView.as_view(), name="page-id"),
    path("<slug:slug>", PageView.as_view(), name="page"),
    path("", PageListView.as_view(), name="home"),
]

cookies/urls.py
from django.urls import path

from .views import reset, update

app_name = "cookies"
urlpatterns = [
    path("reset", reset, name="reset"),
    path("update", update, name="update"),
]

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

urlpatterns = []

tracking/urls.py
from django.urls import path

from .views import dashboard

urlpatterns = [
    path("", dashboard, name="tracking-dashboard"),
]

website/urls.py
import re
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import URLPattern, converters, include, path
from django.utils.html import escapejs
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from .views import (
    account_index,
    export,
    google,
    handler_404,
    handler_500,
    keybase,
    make_error,
    reload_website,
    risc,
    robots,
    sentry,
    songs_list,
    upload_image,
)

handler404 = handler_404
handler500 = handler_500


class OptionalPathConverter:
    """
    Optional path (path that can be empty).
    """

    regex = r".*"

    def to_url(self, value: str):
        return value

    def to_python(self, value):
        return self.to_url(value)


converters.register_converter(OptionalPathConverter, "optpath")


app_name = "website"
urlpatterns: list[list[URLPattern] | URLPattern] = i18n_patterns(
    path("500", make_error),
    path("admin/docs/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", account_index, name="account_index"),
    path("blog/", include("blog.urls", namespace="blog")),
    path("calendrier-avent-2023/", include("calendrier_avent_2023.urls", namespace="calendrier_avent_2023")),
    path("calendrier-avent-2024/", include("calendrier_avent_2024.urls", namespace="calendrier_avent_2024")),
    path("calendrier-avent-2025/", include("calendrier_avent_2025.urls", namespace="calendrier_avent_2025")),
    path("comments/", include("django_comments.urls")),
    path("cookies/", include("cookies.urls", namespace="cookies")),
    path("debug/", include("debug.urls", namespace="debug")),
    path("debug/", include("debug_toolbar.urls")),
    path("export/<format>/<app_label>/<model_name>/<elements_pk>", export, name="export"),
    path("jsi18n", JavaScriptCatalog.as_view()),
    path("pseudos/", include("pseudos.urls", namespace="pseudos")),
    path("reload-website", reload_website),
    path("risc", risc),
    path("sentry", sentry),
    path("songs-list/<optpath:path>", songs_list),
    path("telegram-bot/", include("telegram_bot.urls", namespace="telegram_bot")),
    path("temperatures/", include("temperatures.urls", namespace="temperatures")),
    path("tinymce/upload-image", upload_image, name="tinymce-upload-image"),
    path("tinymce/", include("tinymce.urls")),
    path("tracking/", include("tracking.urls")),
    path("google<str:id>.html", google),
    path("keybase.txt", keybase),
    path("robots.txt", robots),
    path("", include("django.conf.urls.i18n")),
    path("", include("globals.urls")),
    prefix_default_language=False,
)  # type: ignore

if not settings.PRODUCTION:
    SENTRY_DSN = settings.SENTRY_DSN
    if SENTRY_DSN:
        # add a view that gives the custom Sentry loader
        def replace_sentry(request):
            ret = serve(request, "global/sentry.js", document_root=settings.STATIC_ROOT)
            data = b"".join(ret.streaming_content).decode("utf-8")  # type: ignore
            data = re.sub(r'dsn: ?"[^"]*?"', f'dsn: "{escapejs(settings.SENTRY_DSN)}"', data)
            ret.streaming_content = [data.encode("utf-8")]
            return ret

        urlpatterns.append(path(settings.STATIC_URL.strip("/") + "/global/sentry.js", replace_sentry))
        urlpatterns.append(path("sentry.js", replace_sentry))

    if not settings.DEBUG:
        urlpatterns.append(
            path(
                settings.STATIC_URL.strip("/") + "/<path:path>",
                serve,
                {"document_root": settings.STATIC_ROOT},
            )
        )
    urlpatterns.append(
        path(
            settings.MEDIA_URL.strip("/") + "/<path:path>",
            serve,
            {"document_root": settings.MEDIA_ROOT},
        )
    )

website/views.py
import datetime as dt
import hmac
import importlib
import mimetypes
import os.path
import sys
import traceback
from hashlib import sha256
from ipaddress import ip_address, ip_network
from pathlib import Path
from typing import Type
from urllib.parse import quote, urljoin, urlparse
from wsgiref.util import is_hop_by_hop

import requests
from allauth.socialaccount.models import SocialAccount, SocialToken
from allauth.usersessions.models import UserSession
from allauth.usersessions.internal.flows.sessions import end_sessions
from django.apps import apps
from django.conf import settings
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import PermissionDenied
from django.core.serializers import get_serializer
from django.db.models import Model
from django.http import (
    FileResponse,
    Http404,
    HttpRequest,
    HttpResponse,
    HttpResponseForbidden,
    HttpResponseNotAllowed,
    HttpResponseRedirect,
    HttpResponseServerError,
    JsonResponse,
    StreamingHttpResponse,
)
from django.shortcuts import get_object_or_404, redirect, render
from django.template import Engine, RequestContext
from django.urls import resolve
from django.utils.encoding import force_bytes
from django.utils.translation import get_language_from_path
from django.utils.translation import gettext_lazy as _
from django.views.debug import technical_404_response
from django.views.decorators.csrf import csrf_exempt
from sentry_sdk import Hub

from blog.models import Image
from globals.models import Setting
from users.models import User
from website.utils.http import encode_filename
from website.utils.permission import has_permission

from .errors import TestError
from .risc import validate_security_token

try:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))
    fetch = importlib.import_module(".fetch", "scripts").main
except ImportError:
    fetch = None

DATA = Path(__file__).resolve().parent.parent.parent / "data"


def google(_request, id):
    """Return the Google site verification file."""
    if os.getenv("GOOGLE_SITE_VERIFICATION_ID", "") == id:
        return HttpResponse(f"google-site-verification: google{os.getenv('GOOGLE_SITE_VERIFICATION_ID')}.html")
    google_file = DATA / f"google{id}.html"
    if google_file.exists():
        return FileResponse(google_file.open("rb"))
    raise Http404()


def make_error(request):
    """
    This view doesn't return a page, it always fails with `TestError`.
    """
    if 1 + 1 == 2:
        Hub._current.last_event_id = None
        raise TestError("Test of the 500 error page")
    # this will never be called but will hide the type checker error in urls.py
    return HttpResponse()


def handler_404(request, exception):
    """
    404 (not found) error page.
    """
    if request.user and request.user.has_perm("can_see_traceback"):
        return technical_404_response(request, exception)
    return render(
        request,
        "website/404.html",
        {
            "request_path": quote(request.path),
            # "exception": exception_repr,
        },
        status=404,
    )


DEBUG_ENGINE = Engine(
    dirs=[str(Path(__file__).parent / "templates")],
    context_processors=["website.context_processors.globals"],
    debug=True,
    libraries={
        "i18n": "django.templatetags.i18n",
        "nav": "globals.templatetags.nav",
        "socialaccount": "allauth.socialaccount.templatetags.socialaccount",
        "static": "django.templatetags.static",
    },
)


def handler_500(request, _template_name=None):
    """
    500 (server error) page that logs the error.
    """
    try:
        with (Path(__file__).parent / "templates/website/500.html").open() as f:
            t = DEBUG_ENGINE.from_string(f.read())
        html = t.render(
            RequestContext(
                request,
                {
                    "error": True,
                    "error_id": Hub.current._last_event_id or "x" * 32,
                },
            )
        )
        return HttpResponse(html, status=500)
    except Exception:
        # print the exception to the logs
        traceback.print_exc()
        return HttpResponse(_("An unexpected error occured while trying to display the 500 error page."), "text/plain")


def account_index(request):
    return render(request, "account/index.html")


def export(request, format: str, app_label: str, model_name: str, elements_pk: str):
    # Run the operations that don't need the database first
    pk_list = None if elements_pk == "all" else elements_pk.split(",")
    serializer = get_serializer(format)()

    # import this now because it is assigned during serializers loading
    from django.core.serializers import _serializers

    for ext, module in _serializers.items():
        if module.__name__ == serializer.__module__:
            extension = ext
            break
    else:
        extension = "txt"
    if extension == "python":
        extension = "py"

    content_type = get_object_or_404(ContentType, app_label=app_label, model=model_name)
    model = content_type.model_class()

    if not model:
        raise Http404

    # Check for permission
    if not has_permission(request, model):
        if not settings.DEBUG:
            raise Http404
        return HttpResponseForbidden("Permission denied.")

    queryset = model.objects.all()
    if pk_list:
        queryset = queryset.filter(pk__in=pk_list)
    if model.__name__.lower() == "meeting":
        queryset2 = apps.get_model(model._meta.app_label, "Attendance").objects.filter(meeting__in=queryset)
        queryset = list(queryset) + list(queryset2)
    if not isinstance(queryset, list):
        queryset = list(queryset)

    response = HttpResponse()

    date = dt.datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"export_{content_type.app_label}_{content_type.model}_{date}.{extension}"
    response.headers["Content-Type"] = mimetypes.guess_type(f"x.{extension}")[0]  # type: ignore
    response.headers["Content-Disposition"] = "attachment; " + encode_filename(filename)  # type: ignore

    serializer.serialize(queryset, stream=response)
    return response


@csrf_exempt
def reload_website(request: HttpRequest):
    """
    Reload the website with a GET request (for superusers)
    or a POST requests (for GitHub webhook).
    """
    forbidden = HttpResponseForbidden("Permission denied.")
    key = settings.GITHUB_WEBHOOK_KEY
    if not fetch or not key:
        return forbidden

    # The superusers can reload the website
    if request.user.is_superuser:  # type: ignore
        return HttpResponse(fetch(pipe=True), "text/plain")

    if request.method != "POST":
        return HttpResponseNotAllowed(["GET", "POST"])

    # Verify if request came from GitHub
    forwarded_for = request.headers.get("X-Forwarded-For")
    if not forwarded_for:
        return forbidden
    client_ip_address = ip_address(forwarded_for)
    whitelist = requests.get("https://api.github.com/meta").json()["hooks"]

    for valid_ip in whitelist:
        if client_ip_address in ip_network(valid_ip):
            break
    else:
        return forbidden

    # Verify the request signature
    header_signature = request.headers.get("X-Hub-Signature-256")
    if header_signature is None:
        return forbidden

    sha_name, signature = header_signature.split("=", 1)
    if sha_name != "sha256":
        return HttpResponseServerError("Operation not supported.", status=501)

    mac = hmac.new(
        force_bytes(key),
        msg=force_bytes(request.body),
        digestmod=sha256,
    )
    if not hmac.compare_digest(mac.hexdigest(), signature):
        return forbidden

    # If request reached this point we are in a good shape
    # Process the GitHub events
    event = request.headers.get("X-Github-Event", "ping")

    if event == "ping":
        return HttpResponse("pong", "text/plain")
    if event == "push":
        try:
            return HttpResponse(fetch(pipe=True), "text/plain")
        except:  # noqa
            return HttpResponseServerError("Failed to fetch changes")

    # In case we receive an event that's not ping or push
    return HttpResponse(status=204)


def risc(request):
    # Get the token from the request body and validate it
    token = validate_security_token(request.body)

    # We are acting according to the reference document:
    # https://developers.google.com/identity/protocols/risc#error_codes
    for event, data in token["events"].items():
        # Verification
        if event == "https://schemas.openid.net/secevent/risc/event-type/verification":
            # Send a dummy response
            return HttpResponse("pong")

        socialaccount = SocialAccount.objects.select_related("user").get(provider="google", uid=data["subject"]["sub"])

        # Sessions revoked, (all) tokens revoked or account disabled because of hijacking
        if (
            event
            in (
                "https://schemas.openid.net/secevent/risc/event-type/sessions-revoked",
                "https://schemas.openid.net/secevent/oauth/event-type/tokens-revoked",
            )
            or event == "https://schemas.openid.net/secevent/risc/event-type/account-disabled"
            and data["reason"] == "hijacking"
        ):
            # End all the sessions
            end_sessions(request, [UserSession.objects.filter(user=socialaccount.user)])

        # Account disabled not because of bulk activity
        if (
            event == "https://schemas.openid.net/secevent/risc/event-type/account-disabled"
            and data["reason"] != "bulk-account"
        ):
            # Disable login via Google
            socialaccount.delete()

        # Token (associated with this website) revoked
        if event == "https://schemas.openid.net/secevent/oauth/event-type/token-revoked":
            # Delete the tokens associated to that account

website/templates/website/base.html
{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta name="theme-color" content="#ffaa00">
    <link rel="shortcut icon" href="{% static "global/profile_16.jpg" %}">
    <meta name="og:icon" content="{% static "global/profile_16.jpg" %}">

    <title>{% block title %}Mon site{% endblock%}</title>

    {% block cdn_css %}
    <link href="{% static "https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,400;0,700;1,400;1,700&display=swap" %}" rel="stylesheet">
    {% endblock cdn_css %}

    <link rel="stylesheet" href="{% static "global/global.css" %}">
    <link rel="stylesheet" href="{% static "global/header.css" %}">
    <link rel="stylesheet" href="{% static "global/messages.css" %}">
    <link rel="stylesheet" href="{% static "global/audioplayer.css" %}">

    {% block css %}{% endblock %}

    {% block cdn_js %}
    {% if offline %}
    <script src="{% static "vendor/jquery.min.js" %}"></script>
    <script src="{% static "vendor/moment.min.js" %}"></script>
    {% else %}
    {% if SENTRY_SDK and cookies.performance %}
        {% if DEBUG and DEVELOPMENT %}
        <script type="module" src="/sentry.js"></script>
        {% else %}
        <script type="module" src="{% static "global/sentry.js" %}"></script>
        {% endif %}
        {% csrf_token %}
    {% endif %}
    <script src="{% static "https://cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js" %}"></script>
    <script src="{% static "https://cdn.jsdelivr.net/npm/moment@2/moment.min.js" %}"></script>
    {% endif %}
    {% endblock cdn_js %}

    <script src="/jsi18n"></script>
    <script src="{% static "global/global.js" %}"></script>
    <script src="{% static "global/messages.js" %}"></script>
    <script src="{% static "global/audioplayer.js" %}"></script>
    <script src="{% static "global/fancybox.js" %}"></script>
    <script src="{% static "global/navbar.js" %}"></script>

    {% block js %}{% endblock %}

    {% block manifest %}
    <link rel="manifest" href="{% static "global/manifest.json" %}">
    {% endblock %}
    {% block extra_head %}{% endblock extra_head %}
</head>
<body class="{% block body_class %}{% endblock body_class %}">
{% block body %}
<main class="content">{% block content %}{% endblock content %}</main>
{% endblock %}
</body>
</html>

website/templates/website/paginator.html
{% load i18n %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; {% trans "first" %}</a>
            <a href="?page={{ page_obj.previous_page_number }}">{% trans "previous" %}</a>
        {% endif %}

        <span class="current">
            {% blocktrans with current=page_obj.number total=page_obj.paginator.num_pages %}Page {{ current }} of {{ total }}{% endblocktrans %}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">{% trans "next" %}</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">{% trans "last" %} &raquo;</a>
        {% endif %}
    </span>
</div>

website/templates/website/site_base.html
{% extends "website/base.html" %}
{% load i18n %}
{% load nav %}
{% load socialaccount %}
{% load static %}

{% block css %}
    {% if cookies_form %}
    <link rel="stylesheet" href="{% static "cookies/cookies.css" %}">
    {% endif %}
{% endblock css %}

{% block js %}
    {% if not error and cookies_form %}
    {# don't show the cookies form if there is an error #}
    <script src="{% static "cookies/cookies.js" %}"></script>
    {% endif %}
{% endblock js %}

{% block body %}
<div class="navbar">
    <header>
        <a class="title" href="/">
            <img src="{% static "global/profile_100.jpg" %}">
            Mon site
        </a>
        <label class="navbar-burger" for="navbar-is-active">
            <span></span>
            <span></span>
            <span></span>
        </label>
    </header>
    <input type="checkbox" id="navbar-is-active" class="navbar-checkbox sr-only">
    <nav class="navbar-menu">
        <label class="close" for="navbar-is-active"></label>
{{ nav_links|nav }}
        <a href="#" class="navbar-burger" for="navbar-is-active">
            <span></span>
            <span></span>
            <span></span>
        </a>
        <ul></ul>
    </nav>
    <div class="user">
    {% if user.is_authenticated %}
        <details>
            <summary>{{ user.username }}</summary>
            {% if admin_permission %}
            <a href="{% url "admin:index" %}" target="_blank">{% trans "Administration" %}</a><br>
            {% endif %}
            <a href="{% url "account_index" %}">{% trans "Account" %}</a><br>
            <form method="post" action="{% url "account_logout" %}" class="logout-form">
                {% csrf_token %}
                <input type="submit" class="link" value="{% trans "Log out" %}">
            </form>
        </details>
    {% else %}
        <a href="{% url "account_login" %}">{% trans "Log in" %}</a>
    {% endif %}
    </div>
</div>
<div class="main-content">
{% block main-content %}
<main class="content">
{% block content %}{% endblock %}
</main>
{% endblock %}
</div>
<footer class="footer">
    {% block footer %}
    <a href="{{ github_repo }}" target="_blank" class="github-icon"></a>
    <img src="https://github.com/lfavole/website/actions/workflows/django.yml/badge.svg">
    <form method="post" action="{% url "cookies:reset" %}">
        {% csrf_token %}
        <input type="submit" class="link" value="{% trans "Manage cookies" %}">
    </form>
    {% endblock footer %}
</footer>
<ul class="messagelist">
{% if not error %}
    {# don't show the cookies form if there is an error #}
    {% include "cookies/banner.html" %}
{% endif %}
{% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
{% endfor %}
</ul>
{% endblock %}