blog/urls.py
from django.urls import path

from .views import PageListView, PageView

app_name = "blog"
urlpatterns = [
    path("<int:pk>", PageView.as_view(), name="page-id"),
    path("<slug:slug>", PageView.as_view(), name="page"),
    path("", PageListView.as_view(), name="home"),
]

temperatures/urls.py
from django.urls import path

from .views import admin, chart, home

app_name = "temperatures"
urlpatterns = [
    path("chart", chart, name="chart"),
    path("admin", admin, name="admin"),
    path("", home, name="home"),
]

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

urlpatterns = []

tracking/urls.py
from django.urls import path

from .views import dashboard

urlpatterns = [
    path("", dashboard, name="tracking-dashboard"),
]

temperatures/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.formats import date_format, number_format
from django.utils.translation import gettext_lazy as _

from .fields import TemperatureField


class Temperature(models.Model):
    class Weather(models.TextChoices):
        SUNNY = "SUNNY", _("Sunny")
        FEW_CLOUDS = "FEW_CLOUDS", _("Few clouds")
        CLOUDY = "CLOUDY", _("Cloudy")
        RAIN = "RAIN", _("Rain")
        SNOW = "SNOW", _("Snow")

    date = models.DateField(_("Date"))
    temperature = TemperatureField(_("Minimum temperature"))
    weather = models.CharField(
        _("Weather"),
        max_length=15,
        choices=Weather.choices,
        default=Weather.SUNNY,
    )
    wind = models.BooleanField(_("Wind"))
    hail = models.BooleanField(_("Hail"))
    mist = models.BooleanField(_("Mist"))
    snow_cm = models.PositiveIntegerField(_("snow cm"), default=0)
    max_temp = TemperatureField(_("Maximum temperature"), blank=True, null=True)
    notes = models.TextField(_("Notes"), blank=True)

    def clean(self):
        if self.weather == "SNOW":
            if self.snow_cm == 0:
                raise ValidationError(
                    {
                        "snow_cm": _("You must specify the snow cm when it snows."),
                    }
                )
        else:
            self.snow_cm = 0

        if self.max_temp is not None:
            if self.temperature > self.max_temp:
                raise ValidationError(
                    {
                        "max_temp": _("The maximum temperature must be greater than the minimum temperature."),
                    }
                )

    def __str__(self):
        return f"{date_format(self.date)}{_(':')} {number_format(self.temperature)}°C"

    class Meta:
        verbose_name = _("temperature")
        ordering = ["date"]

temperatures/forms.py
import datetime as dt

from django import forms
from temperatures.fields import DateInput, TemperatureInput

from .models import Temperature


def formfield_for_dbfield(db_field, **kwargs):
    if db_field.name == "date":
        # create a date field for today
        return forms.DateField(widget=DateInput, initial=str(dt.date.today()))
    return db_field.formfield(**kwargs)


class TemperaturesForm(forms.ModelForm):
    class Meta:
        model = Temperature
        exclude = []
        widgets = {
            "temperature": TemperatureInput({"autofocus": True}),
            "weather": forms.RadioSelect,
            "max_temp": TemperatureInput(),
        }
        formfield_callback = formfield_for_dbfield
        fieldsets = [
            ("date",),
            ("temperature",),
            ("weather",),
            ("wind", "hail", "mist"),
            ("snow_cm", "max_temp"),
            ("notes",),
        ]

temperatures/views.py
import datetime as dt

from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import TemperaturesForm
from .models import Temperature
from .templatetags.temperatures_utils import missing_extra_days


def admin(request):
    if request.method == "POST":
        form = TemperaturesForm(request.POST)
        if form.is_valid():
            form.save()
            # send the missing / extra days for AJAX requests
            if "ajax" in request.POST:
                return HttpResponse(missing_extra_days())
            # redirect to the same page
            return redirect("temperatures:home")
    else:
        initial_data = {}
        if "date" in request.GET:
            try:
                date = dt.date.fromisoformat(request.GET["date"])
            except ValueError:
                pass
            else:
                initial_data["date"] = str(date)
        form = TemperaturesForm(initial=initial_data)

    return render(request, "temperatures/admin.html", {"form": form})


def chart(request):
    return render(request, "temperatures/chart.html", {"temperatures": Temperature.objects.all()})


def home(request):
    return render(request, "temperatures/home.html")

temperatures/templates/temperatures/admin.html
{% extends "temperatures/base.html" %}
{% load static %}
{% load temperatures_utils %}

{% block css %}
<link rel="stylesheet" href="{% static "temperatures/style.css" %}">
{% endblock css %}
{% block js %}
<script src="{% static "temperatures/script.js" %}"></script>
{% endblock js %}

{% block content %}
{{ block.super }}
<form class="temperatures-form" name="save_temp" method="post" action="{% url "temperatures:home" %}">
    <h1>Enregistrer une température</h1>
    {% missing_extra_days %}
    {% csrf_token %}
    {{ form.as_p }}
    <p><input type="submit"></p>
</form>
{% endblock content %}

temperatures/templates/temperatures/base.html
{% extends "website/site_base.html" %}
{% load static %}
{% load i18n %}

{% block css %}
<link rel="stylesheet" href="{% static "temperatures/style.css" %}">
{% endblock css %}
{% block content %}
<p>
    {% if perms.add_temperature %}<a href="{% url "temperatures:admin" %}">{% trans "Add temperatures" %}</a> –{% endif %}
    <a href="{% url "temperatures:chart" %}">{% trans "Chart" %}</a>
</p>
{% endblock content %}

temperatures/templates/temperatures/chart.html
{% extends "temperatures/base.html" %}
{% load static %}
{% load temperatures_utils %}

{% block title %}Graphique des températures{% endblock title %}
{% block css %}
<link rel="stylesheet" href="{% static "temperatures/highcharts.css" %}">
{% endblock css %}
{% block js %}
<script src="{% static "temperatures/highcharts.js" %}"></script>
<script src="{% static "temperatures/highcharts-boost.js" %}"></script>
<script src="{% static "temperatures/chart.js" %}"></script>
<script id="all-temperatures" type="application/json">{% get_all_temperatures %}</script>
{% endblock js %}

{% block content %}
{{ block.super }}
<h1>Graphique des températures</h1>
<div id="temperatures-chart"></div>
<div id="weather-pie-chart"></div>
{% endblock content %}

temperatures/templates/temperatures/home.html
{% extends "temperatures/base.html" %}