blog/urls.py
from django.urls import path

from .views import PageListView, PageView

app_name = "blog"
urlpatterns = [
    path("<int:pk>", PageView.as_view(), name="page-id"),
    path("<slug:slug>", PageView.as_view(), name="page"),
    path("", PageListView.as_view(), name="home"),
]

calendrier_avent_2023/urls.py
from django.urls import path

from . import views

app_name = "calendrier-avent-2023"
urlpatterns = [
    path("<int:day>", views.day, name="day"),
    path("", views.home, name="home"),
]

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

urlpatterns = []

tracking/urls.py
from django.urls import path

from .views import dashboard

urlpatterns = [
    path("", dashboard, name="tracking-dashboard"),
]

website/urls.py
import re
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import URLPattern, converters, include, path
from django.utils.html import escapejs
from django.views.i18n import JavaScriptCatalog
from django.views.static import serve

from .views import (
    account_index,
    export,
    google,
    handler_404,
    handler_500,
    keybase,
    make_error,
    reload_website,
    risc,
    robots,
    sentry,
    songs_list,
    upload_image,
)

handler404 = handler_404
handler500 = handler_500


class OptionalPathConverter:
    """
    Optional path (path that can be empty).
    """

    regex = r".*"

    def to_url(self, value: str):
        return value

    def to_python(self, value):
        return self.to_url(value)


converters.register_converter(OptionalPathConverter, "optpath")


app_name = "website"
urlpatterns: list[list[URLPattern] | URLPattern] = i18n_patterns(
    path("500", make_error),
    path("admin/docs/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("accounts/", account_index, name="account_index"),
    path("blog/", include("blog.urls", namespace="blog")),
    path("calendrier-avent-2023/", include("calendrier_avent_2023.urls", namespace="calendrier_avent_2023")),
    path("calendrier-avent-2024/", include("calendrier_avent_2024.urls", namespace="calendrier_avent_2024")),
    path("calendrier-avent-2025/", include("calendrier_avent_2025.urls", namespace="calendrier_avent_2025")),
    path("comments/", include("django_comments.urls")),
    path("cookies/", include("cookies.urls", namespace="cookies")),
    path("debug/", include("debug.urls", namespace="debug")),
    path("debug/", include("debug_toolbar.urls")),
    path("export/<format>/<app_label>/<model_name>/<elements_pk>", export, name="export"),
    path("jsi18n", JavaScriptCatalog.as_view()),
    path("pseudos/", include("pseudos.urls", namespace="pseudos")),
    path("reload-website", reload_website),
    path("risc", risc),
    path("sentry", sentry),
    path("songs-list/<optpath:path>", songs_list),
    path("telegram-bot/", include("telegram_bot.urls", namespace="telegram_bot")),
    path("temperatures/", include("temperatures.urls", namespace="temperatures")),
    path("tinymce/upload-image", upload_image, name="tinymce-upload-image"),
    path("tinymce/", include("tinymce.urls")),
    path("tracking/", include("tracking.urls")),
    path("google<str:id>.html", google),
    path("keybase.txt", keybase),
    path("robots.txt", robots),
    path("", include("django.conf.urls.i18n")),
    path("", include("globals.urls")),
    prefix_default_language=False,
)  # type: ignore

if not settings.PRODUCTION:
    SENTRY_DSN = settings.SENTRY_DSN
    if SENTRY_DSN:
        # add a view that gives the custom Sentry loader
        def replace_sentry(request):
            ret = serve(request, "global/sentry.js", document_root=settings.STATIC_ROOT)
            data = b"".join(ret.streaming_content).decode("utf-8")  # type: ignore
            data = re.sub(r'dsn: ?"[^"]*?"', f'dsn: "{escapejs(settings.SENTRY_DSN)}"', data)
            ret.streaming_content = [data.encode("utf-8")]
            return ret

        urlpatterns.append(path(settings.STATIC_URL.strip("/") + "/global/sentry.js", replace_sentry))
        urlpatterns.append(path("sentry.js", replace_sentry))

    if not settings.DEBUG:
        urlpatterns.append(
            path(
                settings.STATIC_URL.strip("/") + "/<path:path>",
                serve,
                {"document_root": settings.STATIC_ROOT},
            )
        )
    urlpatterns.append(
        path(
            settings.MEDIA_URL.strip("/") + "/<path:path>",
            serve,
            {"document_root": settings.MEDIA_ROOT},
        )
    )

calendrier_avent_2023/models.py
from django.db import models
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.utils.translation import gettext_lazy as _

from website.templatetags.format_day import format_day, format_day_html


class Day(models.Model):
    day = models.IntegerField(_("day"), unique=True)
    image = models.ImageField(_("image"))

    class Meta:
        verbose_name = _("Day")

    def __str__(self):
        return mark_safe(format_day(self.day) + " décembre")

    def __html__(self):
        return mark_safe(format_day_html(self.day) + " décembre")

    def get_absolute_url(self):
        return reverse("calendrier_avent_2023:day", args=[self.day])

calendrier_avent_2023/views.py
from datetime import date

from django.http import Http404, HttpRequest
from django.shortcuts import render
from globals.models import Setting

from website.views import has_permission

from .models import Day

DAYS = 25
MONTH = 12
YEAR = 2023
start = date(YEAR, MONTH, 1)
end = date(YEAR, MONTH, 25)


def home(request: HttpRequest):
    today = date.today()
    return render(
        request,
        "calendrier_avent_2023/home.html",
        {"days": range(1, DAYS + 1), "today": today.day if start <= today <= end else -1},
    )


def day(request, day: int):
    has_perm = has_permission(request, Day)
    today = date.today()
    day_date = date(YEAR, MONTH, day)

    try:
        if day == 25:
            day_obj = Setting.objects.get(slug="25-12-2023")
        else:
            day_obj = Day.objects.get(day=day)
    except Day.DoesNotExist:
        day_obj = None  # hide the 404 error if too early (see below)

    if today < day_date and (not has_perm or not bool(request.GET.get("unlock"))):
        return render(
            request,
            "calendrier_avent_2023/too_early.html",
            {
                "day_obj": day_obj,
                "day": day,
                "not_begun": today < start,
                "date_to_wait": start if today < start else day_date,
                "has_perm": has_perm,
            },
        )

    if day_obj is None:
        raise Http404
    return render(
        request,
        "calendrier_avent_2023/day.html",
        {
            "day_obj": day_obj,
            "day": day,
        },
    )

calendrier_avent_2023/templates/calendrier_avent_2023/day.html
{% extends "calendrier_avent_2023/page_base.html" %}
{% load format_day %}

{% block title %}{{ day|format_day }} décembre{% endblock %}

{% block body_class %}day{% endblock body_class %}
{% block content %}
<h1>
    <a href="{% url "calendrier_avent_2023:home" %}"><span class="arrow left-arrow"></span></a>
    {{ day|format_day_html }} décembre
</h1>
{% if day == 25 %}
    {{ day_obj.content|safe }}
{% else %}
    <img src="{{ day_obj.image.url }}">
{% endif %}
{% endblock %}

calendrier_avent_2023/templates/calendrier_avent_2023/home.html
{% extends "calendrier_avent_2023/page_base.html" %}

{% block title %}Calendrier de l'Avent{% endblock %}

{% block body_class %}index{% endblock body_class %}
{% block content %}
<h1>Calendrier de l'Avent</h1>
<div class="jours">{% for day in days %}{% if day == 25 %}
</div>
<div class="jours">{% endif %}
	<a href="{{ day }}"{% if day == today %} class="ajd"{% endif %}>{{ day }}</a>{% endfor %}
</div>
<div class="note-photos">NB : n’hésitez pas à cliquer sur les photos pour les agrandir.</div>
{% endblock %}

calendrier_avent_2023/templates/calendrier_avent_2023/page_base.html
{% extends "website/base.html" %}
{% load static %}

{% block cdn_css %}
{{ block.super }}
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Lobster&amp;display=swap">
{% endblock cdn_css %}
{% block css %}
{{ block.super }}
<link rel="stylesheet" href="{% static "global/countdown.css" %}">
<link rel="stylesheet" href="{% static "calendrier-avent-2023/arrows.css" %}">
<link rel="stylesheet" href="{% static "calendrier-avent-2023/style.css" %}">
{% endblock css %}
{% block js %}
{{ block.super }}
<script src="{% static "global/countdown.js" %}"></script>
<script src="{% static "calendrier-avent-2023/script.js" %}"></script>
{% endblock js %}

{% block body %}
<main>
{% block content %}{% endblock %}
</main>
{% endblock %}

calendrier_avent_2023/templates/calendrier_avent_2023/too_early.html
{% extends "calendrier_avent_2023/page_base.html" %}
{% load format_day %}

{% block title %}{{ day|format_day }} décembre{% endblock %}

{% block content %}
<h1>
    <a href="{% url "calendrier_avent_2023:home" %}"><span class="arrow left-arrow"></span></a>
    {{ day|format_day_html }} décembre
</h1>
<p class="center">
    {% if not_begun %}
    Le calendrier de l’Avent n’a pas encore commencé.
    {% else %}
    Il est trop tôt pour regarder ce jour.
    {% endif %}
    <br>
    <span class="cpt" data-date="{{ date_to_wait.isoformat }}">Revenez plus tard...</span>
</p>
{% if has_perm %}
<p class="center">
    Ou <a href="?unlock=1">cliquez ici</a> pour débloquer.
</p>
{% endif %}
{% endblock %}